<a href="https://colab.research.google.com/github/pranathi000/ML_libraries/blob/main/numpy_for_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NUMPY



Numpy arrays have two more advantages over list and tuple.

List and tuple are in-built data types in python. THey store more than one data type just like a collection of different values.

- Numpy arrays are more advanced than lists and tuples.

- They allows several mathmetical operations to perform.

- The operations we do on numpy arrays are more faster when compared to lists.

In [1]:
import numpy as np
# you can use any abbreviation instead of np.


### Why libraries are used in python?

- Insted of writing 100s of lines of code each time, we store the lines of codes in libraries so that we can just call them by using functions.
- numpy is also a library here

### List Vs Nmpy

In [2]:
import time
from time import process_time

Time taken by a list

In [3]:
python_list = [i for i in range(10000)]
# storing the values from 0 to 10000

start_time = process_time()

In [4]:
python_list = [i+5 for i in  python_list]
# add 5 to all the values in this particular list
end_time = process_time()
# the amount of time required by this process
print(end_time - start_time)

0.6388243080000002


In [6]:
# Lets do the similar process with numpy array too
# declare the numpy array
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

# add 5 to all the values in this particular list
end_time = process_time()
print(end_time - start_time)


0.0016942310000001015


You can see how fast the numpy array is, when comapred with list

Numpy arrays


In [7]:
list1 = [1,2,3,4,5]
print(list1)
print(type(list1))

[1, 2, 3, 4, 5]


In [9]:
np_array = np.array([1,2,3,4,5])
print(np_array)
print(type(np_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


- Take a look! There are no commas betweent the elements in numpy
- nd represents n dimensional array


In [10]:
 # Create a 1D array
a = np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [12]:
#  it gives the information of num of rows and cols in a numpy array
a.shape
# 4 in the output represents that there are 4 columns here

(4,)

In [14]:
# 2D array
b= np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [15]:
b.shape

(2, 4)

In [16]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


If you dont mention any data type the default would be the int data type.

### Initial palceholders in numpy arrays

In some cased we need to initialize an array with all the initial values 0 or may be 1 based on our implementation.



In [19]:
# create a numpy array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
# create a numpy array of one's
y = np.ones((3,2))
print(y)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [22]:
#how can we create an array of a particular value
z = np.full((3,3),7)
print(z)


[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [24]:
# create an identity matrix
# all the diagonal values are 1 and remaining elemens are zero
a = np.eye(4)
# 4 deterenines tht we want 4*4 matrix
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [26]:
# crate anumpy array with random values
np.random.random((4,3))
# all the values are between 0 and 1


array([[0.27982251, 0.63855505, 0.67648876],
       [0.11296226, 0.50836553, 0.1720126 ],
       [0.60066015, 0.8599721 , 0.83333037],
       [0.00389591, 0.92847094, 0.10587581]])

In [27]:
# random integer values array within a specific range
np.random.randint(1,100,(3,5))



array([[88, 94, 61, 79, 96],
       [62, 30, 90,  4, 27],
       [20, 99, 72,  5, 25]])

In [29]:
# array of evenly spaced values
# here we are specifying the number of values we require
np.linspace(10,30,5)

array([10., 15., 20., 25., 30.])

In [33]:
# in here, we can declare the step number
# array of evenly spaced values
e = np.arange(10,31,5)
f = np.arange(10,30,5)
print(e,f)

[10 15 20 25 30] [10 15 20 25]


In [35]:
# converting a list to a numpy array
list2  = [1,2,3,4,5,6,7,8,9]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [36]:
# Analyzing a numpy array
c=np.random.randint(10,90,(5,5))
print(c)

[[68 71 68 33 66]
 [63 73 88 14 60]
 [34 56 80 50 43]
 [84 34 89 49 84]
 [81 35 87 63 88]]


In [39]:
# array dimension
print(c.shape)
print(c.ndim)
#since its a 2D array, it given an output 2

(5, 5)
2


In [40]:
#checking the number of elements present in the array
print(c.size)


25


In [41]:
#checking the data type of the values in the array
print(c.dtype)
# since we initiated the random integer values, the output gives integer type

int64


In [42]:
# mathematical operations that can be performed on a numpy array
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2)
# i we add two lists, the element wise addition is not happening , instead the cocatenation of 2 lists is getting done.


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [43]:
i = 0
for i in range(len(list1)):
  print(list1[i]+list2[i])


7
9
11
13
15


In [44]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[8 6 5]
 [1 4 9]
 [3 2 5]]
[[11 17 19]
 [13 10 15]
 [15 14 13]]


In [48]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)


[[19 23 24]
 [14 14 24]
 [18 16 18]]
[[ -3 -11 -14]
 [-12  -6  -6]
 [-12 -12  -8]]
[[ 88 102  95]
 [ 13  40 135]
 [ 45  28  65]]
[[0.72727273 0.35294118 0.26315789]
 [0.07692308 0.4        0.6       ]
 [0.2        0.14285714 0.38461538]]


- From the above 4 code slides, i just wanna tell you that if we add 2 lists using a + operater it will concatenate the 2 lists instead of performing element wise addition.

- but in the case of numpy array, if we add 2 numpy arrays, element wise addition happens.

In [49]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(np.add(a,b))

[[14 14 24]
 [25 13 23]
 [15 19 16]]


In [51]:
d = np.random.randint(10,20,(2,3))
print(d)
trans_d = np.transpose(d)
print(trans_d)

[[19 12 12]
 [15 17 16]]
[[19 15]
 [12 17]
 [12 16]]


In [52]:
trans2 = d.T
print(trans2)
print(trans2.shape)

[[19 15]
 [12 17]
 [12 16]]
(3, 2)


In [53]:
# reshpaing an array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[0 1 8]
 [8 9 4]]
(2, 3)


In [58]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[0 1]
 [8 8]
 [9 4]]
(3, 2)
