# What is Numpy? A glance



So, NumPy is basically this amazing library in Python that makes handling numbers and data super easy. It's like a super-powered version of Python's built-in lists, but designed for math and data manipulation. You can think of it as the go-to tool for anyone working with numbers or doing machine learning stuff.

* Why should we use NumPy in ML?
Speed: NumPy is super fast compared to regular Python lists because it's optimized for numerical calculations.

* Arrays: It lets you work with arrays (basically tables or grids of data). And arrays are way faster than lists when you're working with large datasets. In machine learning, data is usually in the form of arrays!

* Math Stuff: NumPy has tons of built-in functions to do all sorts of math. Whether you’re adding arrays, multiplying them, or doing fancy matrix operations, NumPy’s got your back. And trust me, ML loves math!

* Works Great with Other Libraries: NumPy is like the best friend of libraries like Pandas, Scikit-learn, and TensorFlow. So if you’re diving into ML, NumPy will definitely be in the picture.

### Why is Google Colab Better for Learning?
So, YouTube videos are great and all, but they’re mostly about watching and listening, right? But when you’re coding, it’s all about doing.

* Instant Feedback: You type some code, hit "Run," and boom, you see the result. If it doesn’t work, you can fix it on the spot. No waiting around.

* No Setup: You don’t have to deal with installing stuff on your computer. It’s all set up in the cloud. Just go to Colab and start coding.

* Hands-On Practice: Colab is like a coding playground. You can try out examples and experiment with code. It’s like learning to ride a bike—you gotta try it yourself, not just watch someone else.

* Visual Learning: With Colab, you can create plots and graphs using libraries like Matplotlib, so you can actually see how things are changing when you mess with arrays and numbers. It helps everything click.


# Learning NUMPY

In [1]:
import numpy as np
print(np.__version__)

1.26.4


*Lets start with the concept of arrays! Create our first numpy array.
observe that we have used () and inside the braces we created an arrat with [  ] where elements are inside the square braces. I hope your are a bit familiar with python since u have up here to learn numpy!*





In [2]:
arr = np.array([1,2,3,4,5])
print("Our Array: ",arr)
print("type of array thar we have created: ",type(arr))

Our Array:  [1 2 3 4 5]
type of array thar we have created:  <class 'numpy.ndarray'>


In [5]:
# 1D array
arr_1d = np.array([10, 20, 30])

# 2D array (matrix)
arr_2d = np.array([[1, 2], [3, 4]])

# 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("1D Array:", arr_1d)
print("2D Array:\n", arr_2d)
print("3D Array:\n", arr_3d)


1D Array: [10 20 30]
2D Array:
 [[1 2]
 [3 4]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


(1,2,2,2) determines that there is one block and there are 2 sublocks inside a block. Each group has 2 rows and each row has 2 elements.
Batch 1 (1 group):
  Sub-group 1:

    Row 1: [a, b]
    Row 2: [c, d]

  Sub-group 2:
  
    Row 1: [e, f]
    Row 2: [g, h]


In [12]:
print(arr_2d.shape)
print(arr_3d.shape)

(2, 2)
(1, 2, 2, 2)


In [13]:
print(arr_2d.size)
print(arr_3d.size)

4
8


If you want to find a particular element in the array, you can use slicing. Remembrer thar arrays are 0 indexed!

In [17]:
print("element at index 1 is : ",arr[1])

element at index 1 is :  2


you can also use user input method in orer find the element by entering its position. However, it leaves an error if you give an index which is out of bound

In [18]:
# n= int(input("enter a number : "))
# print("element ar index",n, "is", arr[n])

## How to solve the error if you give the Index more than size of an array?
Here comes the try and except block to handle the errors from happening

In [20]:
n= int(input("enter a number : "))
try:
    print("Element at index", n, "is", arr[n])
except:
      print(f"Error: Index {n} is out of bounds. The array has indices from 0 to {len(arr) - 1}.")


enter a number : 15
Error: Index 15 is out of bounds. The array has indices from 0 to 4.


*You can also use if else statements to handle them.

I think its normal to imagine that the elements with in the range of array

0 <= n < len(arr) gives us the output eles throws an error*



In [ ]:
arr = np.array([10, 20, 30, 40])

n = int(input("Enter a number: "))

# Check if the index is valid
if 0 <= n < len(arr):
    print("Element at index", n, "is", arr[n])
else:
    print(f"Invalid index {n}. Please enter a number between 0 and {len(arr) - 1}.")


you can use the concept of slicing if required

In [21]:
# Slicing
print("Slice [1:4]:", arr[1:4])

Slice [1:4]: [2 3 4]


If you want to reshape or convert an array from 1D to 2D or constrict the number of rows ro a particualr value, u can do it with the help of .reshape(   )

In [27]:

arr1 = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr1.reshape(2, 3)  # Reshape to 2 rows, 3 columns

print(new_arr)

[[1 2 3]
 [4 5 6]]


Some slicing examples are given below

In [36]:
# lets consider an array of 10 elements
arr2 = [0,1,2,3,4,5,6,7,8,9]
print("elements from the position 2 to 5: \n",arr2[2:5]) #  [2, 3, 4] we asked upto 5th position , but remember that it gives a position 1 less the position we give
# Slice with step size
print(arr2[2::7])

print(arr2[::2])

# Reverse the array
print(arr2[::-1])

elements from the position 2 to 5: 
 [2, 3, 4]
[2, 9]
[0, 2, 4, 6, 8]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]



## How slicing is used in ML?
Machine learning models need data to be split into training and testing sets.

*   Slicing helps separate data efficiently.
*   In datasets with many features, slicing can extract specific columns for analysis or training.
*   Slicing is used to crop or focus on specific parts of an image when performing data augmentation.
*   While debugging, you might only need a subset of the dataset to analyze specific patterns.


If you don’t know the length of the array in advance, you can start with an empty array (or list) and dynamically append values. Once you're done, convert it to a NumPy array.

In [37]:

# Start with a Python list
temp_list = []

# Dynamically add elements
for i in range(5):  # Example loop, change as needed
    value = i * 10  # Generate some value
    temp_list.append(value)

# Convert the list to a NumPy array
dynamic_array = np.array(temp_list)

print("Dynamic Array:", dynamic_array)


Dynamic Array: [ 0 10 20 30 40]


Predefining Size with Zeros or Placeholders
When you have an idea about the maximum size (even roughly), you can predefine it for efficiency:

In [39]:
# Predefine an array with zeros
predefined_array = np.zeros(10)  # Max size of 10

# Fill it dynamically
for i in range(5):  # Use only first 5 spots
    predefined_array[i] = i + 1

# Slice to keep only the filled part
final_array = predefined_array[:10]
print("Efficient Array:", final_array)


Efficient Array: [1. 2. 3. 4. 5. 0. 0. 0. 0. 0.]


In [ ]:
arr4 = np.array([1, 2, 3])

filtered_array = arr4[arr4 > 1]

# Array Functions

using np.append(   )

In [41]:
arr3 = np.array([1, 2, 3])
new_arr = np.append(arr3, [4, 5])
print("Extended Array:", new_arr)


Extended Array: [1 2 3 4 5]


using np.concatenate(  )





In [47]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
merged = np.concatenate((arr1, arr2))
print("Merged Array:", merged)


Merged Array: [1 2 3 4 5 6]


np.ones(  )

In [50]:
arr5 = np.ones(10)
print(arr5)


ones_array = np.ones((3, 4))  # A 3x4 array of ones
print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


np.zeros(   )

In [51]:
arr5 = np.zeros(10)
print(arr5)
zeros_array = np.zeros((2, 3))  # A 2x3 array of zeros
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


np.full(  )

In [52]:
full_array = np.full((2, 3), 7)  # A 2x3 array filled with 7
print(full_array)


[[7 7 7]
 [7 7 7]]


np.arrange(  )

In [53]:
arange_array = np.arange(0, 10, 2)  # Array from 0 to 10 with step size of 2
print(arange_array)


[0 2 4 6 8]


np.linspcae(  )
We'll learn more about linspace in further lessons

In [ ]:
linspace_array = np.linspace(0, 10, 5)  # 5 points between 0 and 10
print(linspace_array)


np.eye(  )

In [54]:
eye_array = np.eye(3)  # A 3x3 identity matrix
print(eye_array)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


np.random.rand(  )

In [55]:
random_array = np.random.rand(2, 3)  # 2x3 array of random values between 0 and 1
print(random_array)


[[0.08063533 0.5050977  0.71442176]
 [0.01357062 0.30797033 0.34248819]]


np.random.randint(  )

In [56]:
randint_array = np.random.randint(1, 10, size=(3, 3))  # Random integers between 1 and 10 in a 3x3 array
print(randint_array)


[[4 2 1]
 [8 1 8]
 [8 8 5]]


np.repeat()

In [57]:
repeat_array = np.repeat([1, 2, 3], 3)  # Repeat each element 3 times
print(repeat_array)


[1 1 1 2 2 2 3 3 3]


# How these functions are used in ML?

***1. np.ones()***

Creates arrays filled with 1s, often for initializing bias terms in models.

***2. np.zeros()***

Creates arrays filled with 0s, commonly used for initializing weights or representing missing data.

***3. np.full()***

Fills arrays with a specific value, useful for padding or initialization.

***4. np.arange()***

Generates sequences of numbers, helpful for creating indices or splitting datasets.

***5. np.linspace()***

Generates evenly spaced values between two numbers, often used for tuning hyperparameters or visualizations.

***6. np.eye()***

Creates an identity matrix, used in regularization or optimization tasks.

***7. np.random.rand()***

Generates random numbers between 0 and 1, commonly used for random initialization of weights.

***8. np.random.randint()***

Generates random integer values, useful for creating labels or shuffling data.

***9. np.repeat()***

Duplicates elements in an array, useful for repeating values or data augmentation.

***10. np.reshape()***

Changes the shape of an array, necessary for reshaping data or flattening images.