[Google Colab](https://colab.research.google.com/drive/) You can open google colab to practice the codes.

```
# This is formatted as code
```



# Lesson 2: Array Manipulation and Basic Mathematical Functions

***Topics to Cover:***
Array Reshaping & Flattening



```
reshape()
flatten()
np.expand_dims()
np.squeeze()
```


### Mathematical Functions

Element-wise arithmetic operations: addition, subtraction, multiplication, division
Basic statistical functions: np.sum(), np.mean(), np.min(), np.max(), np.std()

1. np.sum()
2. np.sum()
3. np.mean()
4. np.min()
5. np.max()
6. np.std()

### Array Broadcasting

Concept of broadcasting
Broadcasting between arrays of different shapes
Scalar broadcasting
Basic Statistical Functions

Calculating mean, median, standard deviation, and variance


In [18]:
import numpy as np

In [19]:
arr = np.arange(12)
# since number elemnts such 1,2,3,4 are not given, it takes the elements from 0 to 11 as we provided upto 12
# you can also give any number instead of 12
reshaped_arr = arr.reshape(3,4)
# we wanna reshape the arrat with 3 rows and 4 columns
print("Reshaped Array:\n", reshaped_arr)

Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Remember that, it's not *arrange* it's **arange** .

What if we want to convert the 2D array back into 1D array?
Instead of creating a diff array and elemeting it, you can convert using a method called flatten().
Take the reshaped array, above and flatten it again


In [20]:
# Flattening the 2D array back into 1D
flattened_arr = reshaped_arr.flatten()
print("Flattened Array:", flattened_arr)


Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


Lets expand the dimensions of reshaped array to create a 3D array

In [21]:
expanded_arr = np.expand_dims(reshaped_arr,axis=0) #axis=0 row wise
print("Expanded Array (1x3x4):\n", expanded_arr)


Expanded Array (1x3x4):
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


we use expand_dims() to expand it

In [22]:
expanded_arr = np.expand_dims(reshaped_arr,axis=1) #axis=1 col wise
print("Expanded Array (1x3x4):\n", expanded_arr)


Expanded Array (1x3x4):
 [[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]


In [23]:
# Create a 3D array of shape (1, 3, 1)
arr4 = np.array([[[0], [1], [2]]])

print("Original Array Shape:", arr4.shape)
# here (1,3,1) refers that there is 1 block,3 sub blocks, and 1 element in each sub block

Original Array Shape: (1, 3, 1)


squeeze(  ) helps in surpressing more dimensional array in into single dimensional arr.

In [24]:
# Squeezing the array
squeezed_arr = np.squeeze(arr4)
print("Squeezed Array Shape:", squeezed_arr.shape)
print("Squeezed Array:\n", squeezed_arr)

Squeezed Array Shape: (3,)
Squeezed Array:
 [0 1 2]


# Mathematical Functions

In [25]:
import numpy as np
my_arr1 = np.array([1,2,3,4,5])
my_arr2 = np.array([6,7,8,9,10])
sum_arr = my_arr1 + my_arr2
print("Sum Array:", sum_arr)


# Element-wise subtraction
sub_arr = my_arr1 - my_arr2
print("Subtraction:", sub_arr)

# Element-wise multiplication
mul_arr = my_arr1 * my_arr2
print("Multiplication:", mul_arr)

# Element-wise division
div_arr = my_arr1 / my_arr2
print("Division:", div_arr)

Sum Array: [ 7  9 11 13 15]
Subtraction: [-5 -5 -5 -5 -5]
Multiplication: [ 6 14 24 36 50]
Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


How to add two unequal arrays?
* Here we have to append zeros to the end of the array which is small
* we consider the lenth of the bigger array to be the result of the array
* First find out the max length of the any given array.
* we use np.pad() to append the zeros. No need to append any zeros to the bigger array.
* The constant_values=0 ensures the padding values are 0. If this parameter were omitted or set to a different value, the padding might default to another value or behavior, which would result in incorrect sums.

In [26]:

def add_arrays_numpy(my_arr1, my_arr2):
    max_len = max(len(my_arr1), len(my_arr2))
    my_arr1 = np.pad(my_arr1, (0, max_len - len(my_arr1)), constant_values=0)
    my_arr2 = np.pad(my_arr2, (0, max_len - len(my_arr2)), constant_values=0)
    return my_arr1 + my_arr2

result = add_arrays_numpy(my_arr1, my_arr2)
print(result)  # Output: [5 7 3]


[ 7  9 11 13 15]


The same applies for subtraction , multiplication and division.


# Statistical Functions

Numpy is inbuit with some statistical operations instead of doing them manually through code.
* They are much handy while organising data, calculating mean and more...

In [27]:
sum_val = np.sum(my_arr1)
print("Sum:", sum_val)

mean_val =  np.mean(my_arr1)
print("Mean:", mean_val)

min_val = np.min(my_arr1)
print("Min:", min_val)

max_val = np.max(my_arr1)
print("Max:", max_val)

# Standard deviation
std_val = np.std(my_arr1)
print("Standard Deviation:", std_val)

Sum: 15
Mean: 3.0
Min: 1
Max: 5
Standard Deviation: 1.4142135623730951


# Array broadcasting

In [28]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([10, 20])

# Broadcasting arr2 (1D) to match arr1 (2D)
broadcasted_arr = arr1 + arr2
print("Broadcasted Array:\n", broadcasted_arr)
#  10+1 10+3 20+2 20+4

Broadcasted Array:
 [[11 22]
 [13 24]]


### Scalar Broadcasting

In [29]:
# Broadcasting a scalar value to an array
# To add any scalar value to the multi dimensional array
scalar = 5
scalar_broadcasted_arr = arr1 + scalar
print("Scalar Broadcasted Array:\n", scalar_broadcasted_arr)


Scalar Broadcasted Array:
 [[6 7]
 [8 9]]


When coming to the more basic statistical Functions which are like heart of ML such as mean , median, variance, etc can be easily computed by direct methods.

In [30]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Mean
mean_val = np.mean(arr)
print("Mean:", mean_val)

# Median
median_val = np.median(arr)
print("Median:", median_val)

# Standard Deviation
std_val = np.std(arr)
print("Standard Deviation:", std_val)

# Variance
var_val = np.var(arr)
print("Variance:", var_val)


Mean: 5.0
Median: 5.0
Standard Deviation: 2.581988897471611
Variance: 6.666666666666667


### calculating Percentage:
25th Percentile (Q1):
Position:
0.25
×
(
𝑛
−
1
)

𝑛
n is the number of elements.
0.25
×
4
=
1.0
, so take the value at index 1, which is 20.


75th Percentile (Q3):
Position:
0.75
×
(
𝑛
−
1
)

0.75
×
4
=
3.0
, so take the value at index 3, which is 40.

In [31]:
data = [10, 20, 30, 40, 50]
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)
print("25th Percentile:", percentile_25, "75th Percentile:", percentile_75)


25th Percentile: 20.0 75th Percentile: 40.0


In [32]:
x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]

cov_matrix = np.cov(x, y)
print("Covariance Matrix:\n", cov_matrix)


Covariance Matrix:
 [[ 2.5  5. ]
 [ 5.  10. ]]


Input Arrays:

𝑥
=
[
1
,
2
,
3
,
4
,
5
]


𝑦
=
[
2
,
4
,
6
,
8
,
10
]

Correlation Calculation:

The relationship between x and y is perfectly linear:
𝑦
=
2
𝑥

The correlation coefficient is 1 because as x increases, y increases proportionally.

In [33]:
x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]

corr_coef = np.corrcoef(x, y)
print("Correlation Coefficient Matrix:\n", corr_coef)


Correlation Coefficient Matrix:
 [[1. 1.]
 [1. 1.]]


**Lesson 2: Array Manipulation and Basic Mathematical Functions in ML Context
Array Reshaping & Flattening**

* reshape(): Useful for reshaping datasets into compatible input/output formats for models.
* flatten(): Converts multidimensional data (e.g., images) into a 1D array for ML algorithms.
* np.expand_dims(): Adds an axis to data, often used when a model expects additional dimensions (e.g., for batch size).
* np.squeeze(): Removes unnecessary dimensions to simplify the data structure (e.g., after model predictions).
Adding/Removing Dimensions

Ensures compatibility with ML models by aligning the input/output shapes.
Mathematical Functions
Addition, Subtraction, Multiplication, Division: Perform element-wise operations for data augmentation or preprocessing.
* np.sum(): Aggregates data, such as summing feature values or losses.
* np.mean(): Calculates averages, used in metrics like Mean Squared Error (MSE).
* np.min() and np.max(): Identify feature ranges for normalization or scaling.
* np.std(): Computes the standard deviation, crucial for standardizing data.

**Array Broadcasting**
* Concept of broadcasting: Aligns smaller arrays with larger ones during operations without explicit reshaping.
* Broadcasting between different shapes: Efficient for batch processing and element-wise operations in ML.
* Scalar broadcasting: Applies scalar operations across entire datasets (e.g., scaling pixel values in images).
**Basic Statistical Functions**
* Mean, Median, Standard Deviation, Variance: Provide insights into data distribution for preprocessing and feature scaling.
* Covariance and Correlation: Measure relationships between features, aiding in feature selection.
**Applications in Machine Learning**
* Reshaping: Prepare data for models (e.g., images reshaped to (-1, 28, 28) for CNNs).
* Flattening: Convert data for dense layers or traditional ML models.
* Element-wise operations: Normalize or augment datasets.
* Broadcasting: Simplifies batch computations in neural networks.
* Statistical functions: Analyze and preprocess datasets for better model performance.

***Here is my Lesson1 in case if you haven't looked at it before!***
[Github: pranathi000](https://github.com/pranathi000/ML_libraries/blob/main/Numpy/1_Basics_of_numpy_arrays.ipynb)