# Lesson 4: Matrix Operations with NumPy

### Matrix Multiplication

This colab notebook is gonna be a bit longer than the previous ones. So there is a need to know matrices and how they work in ML inorder to train any model!
1.np.dot() :

  * ***a) The np.dot()*** function performs the dot product of two arrays. For 2D arrays (matrices), it calculates the matrix product.



In [23]:
# Let's import numpy
import numpy as np
# you can import numpy with n or num or anything . Not necessarily np

In [24]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
result = np.dot(a,b)
print(result)
# Here every row element is multipled with every column element on the 2nd matrix and then added up
# [(1*5)+(2*7)   (1*6)+(2*8)]
# [(3*5)+(4*7)   (3*6)_(4*8)]

[[19 22]
 [43 50]]


**Why it’s Important in ML:**

Matrix multiplication is at the heart of deep learning. For example, multiplying weights with inputs in neural networks to compute layer outputs.



* b) Using the ***@ Operator***
It is a shorthand for matrix multiplication.




In [25]:
result_at = a @ b
print("Matrix Multiplication Result (@ operator):\n", result_at)
# We'll get the same result

Matrix Multiplication Result (@ operator):
 [[19 22]
 [43 50]]


**Why it’s Important in ML:**

It provides a clean and concise way to represent matrix operations, crucial for large-scale computations in ML.

c) ***Element-wise Multiplication (*)***

Multiplies corresponding elements of Two Matrices

In [26]:
element_wise = a * b
print("Element-wise Multiplication Result:\n", element_wise)


Element-wise Multiplication Result:
 [[ 5 12]
 [21 32]]


**Why it’s Important in ML:**

Used for operations like applying element-wise activation functions or manipulating specific parts of data.

### Inverse and Transpose of Matrices

a) **Matrix Inverse (np.linalg.inv())**

The inverse of a matrix
𝐴 satisfies
𝐴
⋅
𝐴
−
1
=
𝐼

𝐼
is the identity matrix where the diagonal elements are 1.

In [27]:
# lets take a new matrix
c = np.array([[1,2],[3,4]])
inverse = np.linalg.inv(c)
print("Matrix Inverse:\n", inverse)


# Verify the result
identity = np.dot(c, inverse)
print("Verification (C * C^-1):\n", identity)

Matrix Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Verification (C * C^-1):
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


If in case you are unfamiliar on [How to find A inverse](https://byjus.com/maths/find-inverse-of-matrix/)

Ik that u are new to linalg which will see in the same notebook! Cool!

**Why it’s Important in ML:**

Matrix inverses are used to solve linear systems and in optimization problems like least-squares regression.

---

b) ***Matrix Transpose (np.transpose() or .T)*** :
Flips a matrix over its diagonal, swapping rows with columns.

**Why it’s Important in ML:**
Transposes are useful when switching between row and column representations, e.g., in covariance matrices or backpropagation in neural networks.



In [28]:
transpose = np.transpose(c)
print("Transpose of Matrix C:\n", transpose)

# Alternatively
transpose_T = c.T
print("Transpose of Matrix C (using .T):\n", transpose_T)


Transpose of Matrix C:
 [[1 3]
 [2 4]]
Transpose of Matrix C (using .T):
 [[1 3]
 [2 4]]


#  Matrix Methods



---

### Eigen Values and Eigen Vectors



Eigenvalues and eigenvectors are properties of square matrices. They play a role in dimensionality reduction (PCA).

**Why it’s Important in ML:**

Eigenvalues and eigenvectors are used in PCA for reducing the dimensionality of data while retaining its variance

In [29]:
# Define a square matrix
D = np.array([[2, 0], [0, 3]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(D)
print("Matrix D:\n", D)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Matrix D:
 [[2 0]
 [0 3]]
Eigenvalues:
 [2. 3.]
Eigenvectors:
 [[1. 0.]
 [0. 1.]]


### Solving Systems of Equations (np.linalg.solve)

**Why it’s Important in ML:**

Systems of equations arise in optimization, linear regression, and solving constraints in ML models.

In [30]:
# Coefficient matrix (A) and constant matrix (b)
A = np.array([[3, 1], [1, 2]])
B = np.array([9, 8])

# Solve for x
solution = np.linalg.solve(A, B)
print("Solution of the System Ax = b:\n", solution)


Solution of the System Ax = b:
 [2. 3.]


### Determinant of a Matrix (np.linalg.det())
The determinant is a scalar value that provides insights into the properties of a matrix, such as whether it is invertible. If the determinant is
0, the matrix is singular and cannot be inverted.

**Why it’s Important in ML:**

The determinant is used in algorithms like Gaussian elimination and calculating matrix inverses. In ML, it plays a role in transformations and evaluating model stability.

In [31]:
import numpy as np

# Define a square matrix
A = np.array([[4, 7], [2, 6]])

# Compute the determinant
determinant = np.linalg.det(A)
print("Matrix A:\n", A)
print("Determinant of A:", determinant)


Matrix A:
 [[4 7]
 [2 6]]
Determinant of A: 10.000000000000002


### Singular Value Decomposition (SVD) (np.linalg.svd())
SVD decomposes a matrix
𝐴
A into three matrices
𝑈
,
Σ
,
 and
𝑉
𝑇
(v transpose)

 . It is widely used in dimensionality reduction and noise filtering.

 SVD decomposes a matrix
𝐵 into three components:

𝐵
=
𝑈
⋅
Σ
⋅
𝑉
𝑇

Where:

𝑈
: A matrix of left singular vectors (orthogonal, size
𝑚
×
𝑚
m×m).

Σ
: A diagonal matrix containing singular values (non-negative, size
𝑚
×
𝑛
m×n).

𝑉
𝑇
 : A matrix of right singular vectors (orthogonal, size
𝑛
×
𝑛
n×n).

* The columns of
𝑈 are the eigenvectors of
𝐵
⋅
𝐵
𝑇

* The singular values are the square roots of the eigenvalues of
𝐵
⋅
𝐵
𝑇
  or
𝐵
𝑇
⋅
𝐵
ingular values:
Σ
=
diag(sqrt
(
𝜆
1
,
𝜆
2
))

* Where
𝜆
1
,
𝜆
2 are the eigenvalues of
𝐵
𝑇
⋅
𝐵

* The rows of
𝑉
𝑇are the eigenvectors of
𝐵
𝑇
⋅
𝐵


**Why it’s Important in ML:**
SVD is the backbone of Principal Component Analysis (PCA), used in data compression and feature extraction.

In [32]:
# Define a matrix
B = np.array([[1, 2], [3, 4], [5, 6]])

# Perform SVD
U, Sigma, Vt = np.linalg.svd(B)
print("Matrix B:\n", B)
print("U:\n", U)
print("Sigma:\n", Sigma)
print("V^T:\n", Vt)


Matrix B:
 [[1 2]
 [3 4]
 [5 6]]
U:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Sigma:
 [9.52551809 0.51430058]
V^T:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


***Why SVD is Important in ML?***

*Dimensionality Reduction:*

* Used in PCA to reduce the feature space for better visualization and model performance.

*Noise Filtering:*

* Helps remove noise by reconstructing data using only significant singular values.

*Matrix Approximation:*

* Low-rank approximations are used in recommender systems.

### QR Decomposition (np.linalg.qr())
QR decomposition splits a matrix
𝐴 into an orthogonal matrix
𝑄 and an upper triangular matrix
𝑅.

**Why it’s Important in ML:**
QR decomposition is used in solving linear regression problems and for numerical stability in computations.

In [33]:
# Define a matrix
C = np.array([[1, 2], [3, 4], [5, 6]])

# Perform QR decomposition
Q, R = np.linalg.qr(C)
print("Matrix C:\n", C)
print("Q:\n", Q)
print("R:\n", R)

Matrix C:
 [[1 2]
 [3 4]
 [5 6]]
Q:
 [[-0.16903085  0.89708523]
 [-0.50709255  0.27602622]
 [-0.84515425 -0.34503278]]
R:
 [[-5.91607978 -7.43735744]
 [ 0.          0.82807867]]


### Norm of a Matrix or Vector (np.linalg.norm())
The norm measures the magnitude of a vector or matrix, such as the Euclidean norm or Frobenius norm.

**Why it’s Important in ML:**

Norms are used in regularization techniques like L2 regularization to prevent overfitting.

In [34]:
# Define a vector and a matrix
vector = np.array([3, 4])
matrix = np.array([[1, 2], [3, 4]])

# Compute norms
vector_norm = np.linalg.norm(vector)
matrix_norm = np.linalg.norm(matrix, 'fro')  # Frobenius norm
print("Vector:\n", vector)
print("Norm of Vector:", vector_norm)
print("Matrix:\n", matrix)
print("Frobenius Norm of Matrix:", matrix_norm)


Vector:
 [3 4]
Norm of Vector: 5.0
Matrix:
 [[1 2]
 [3 4]]
Frobenius Norm of Matrix: 5.477225575051661


### Rank of a Matrix (np.linalg.matrix_rank())
The rank of a matrix is the dimension of the column space. It determines the number of linearly independent columns.

**Why it’s Important in ML:**

Matrix rank helps in identifying redundancy in data and is crucial for understanding the feasibility of linear systems.

In [35]:
# Define a matrix
D = np.array([[1, 2], [2, 4]])

# Compute the rank
rank = np.linalg.matrix_rank(D)
print("Matrix D:\n", D)
print("Rank of D:", rank)


Matrix D:
 [[1 2]
 [2 4]]
Rank of D: 1


### Trace of a Matrix (np.trace())
The trace is the sum of the diagonal elements of a square matrix.

**Why it’s Important in ML:**

The trace is used in optimization problems, such as in covariance matrix calculations in statistical ML.

In [36]:
# Define a square matrix
E = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Compute the trace
trace = np.trace(E)
print("Matrix E:\n", E)
print("Trace of E:", trace)


Matrix E:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Trace of E: 15


### Solving Overdetermined or Underdetermined Systems (np.linalg.lstsq())

This method finds the least-squares solution to
𝐴
𝑥
=
𝑏 when
𝐴
 is not square.

**Why it’s Important in ML:**

Least-squares solutions are used in regression models to find the best fit for data.

In [37]:
# Coefficient matrix and constants
A = np.array([[1, 1], [1, 2], [1, 3]])
b = np.array([6, 5, 7])

# Solve using least squares
x, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)
print("Least-squares solution x:", x)
print("Residuals:", residuals)


Least-squares solution x: [5.  0.5]
Residuals: [1.5]


### Rank of a Matrix (np.linalg.matrix_rank)
The rank of a matrix is the number of linearly independent rows or columns. It is essential in determining whether a matrix is full-rank, which is crucial for solving linear equations.

**Why It's Important in ML?**

Feature Engineering: Determines the dimensionality of the feature space.

Data Consistency: Helps verify whether a dataset has redundant or dependent features.

In [38]:
import numpy as np

# Define a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Compute the rank
rank = np.linalg.matrix_rank(matrix)

print("Matrix:\n", matrix)
print("Rank of the matrix:", rank)


Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Rank of the matrix: 2


### Moore-Penrose Pseudoinverse (np.linalg.pinv)
The pseudoinverse is used when a matrix is not invertible (singular) but we still need an approximate solution for linear systems.

**Why It's Important in ML?**

* Linear Regression: Used to solve normal equations when
(𝑋
𝑇)(X transpose)
𝑋 where
 X is not invertible.

* Overdetermined/Underdetermined Systems: Finds solutions when there are more equations than variables or vice versa.

Learn more about this topic [here](https://www.geeksforgeeks.org/moore-penrose-pseudoinverse-mathematics/)


In [39]:
# Define a non-square matrix
A = np.array([[1, 2], [3, 4], [5, 6]])

# Compute the pseudoinverse
pseudo_inv = np.linalg.pinv(A)

print("Matrix A:\n", A)
print("Pseudoinverse of A:\n", pseudo_inv)


Matrix A:
 [[1 2]
 [3 4]
 [5 6]]
Pseudoinverse of A:
 [[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]


### QR Decomposition (np.linalg.qr)
QR decomposition expresses a matrix
𝐴 as
𝐴
=
𝑄
𝑅 where
𝑄 is an orthogonal matrix and
𝑅 is an upper triangular matrix.

**Why It's Important in ML?**

Solving Linear Systems: QR decomposition is used in least squares problems.

Eigenvalue Problems: A step in algorithms for eigenvalue computation.

In [40]:
# Define a matrix
B = np.array([[1, 2], [3, 4], [5, 6]])

# Perform QR decomposition
Q, R = np.linalg.qr(B)

print("Matrix B:\n", B)
print("Q (Orthogonal Matrix):\n", Q)
print("R (Upper Triangular Matrix):\n", R)


Matrix B:
 [[1 2]
 [3 4]
 [5 6]]
Q (Orthogonal Matrix):
 [[-0.16903085  0.89708523]
 [-0.50709255  0.27602622]
 [-0.84515425 -0.34503278]]
R (Upper Triangular Matrix):
 [[-5.91607978 -7.43735744]
 [ 0.          0.82807867]]


### Hadamard Product (Element-Wise Multiplication)


In [41]:
# Define two matrices
F = np.array([[1, 2], [3, 4]])
G = np.array([[5, 6], [7, 8]])

# Compute the Hadamard product
hadamard_product = F * G

print("Matrix F:\n", F)
print("Matrix G:\n", G)
print("Hadamard Product:\n", hadamard_product)


Matrix F:
 [[1 2]
 [3 4]]
Matrix G:
 [[5 6]
 [7 8]]
Hadamard Product:
 [[ 5 12]
 [21 32]]


### Diagonal of a Matrix (np.diag)

In [42]:
# Extract diagonal
H = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
diagonal = np.diag(H)

# Create diagonal matrix
diag_matrix = np.diag([1, 2, 3])

print("Matrix H:\n", H)
print("Diagonal of H:", diagonal)
print("Diagonal Matrix:\n", diag_matrix)


Matrix H:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Diagonal of H: [1 5 9]
Diagonal Matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
