# Lesson 5: Eigenvalues, Eigenvectors, and Advanced Linear Algebra Concepts

In [1]:
import numpy as np

### Why eigenvalues are imp in ML?
* Dimensionality Reduction: Eigenvalues help in reducing the number of features (dimensions) in the dataset (e.g., Principal Component Analysis or PCA), which simplifies the model and speeds up training.

* Understanding Data Structure: Eigenvalues help to understand the spread and orientation of data, aiding in better data preprocessing and visualization.

* Stability of Models: In some models, eigenvalues indicate the stability of the model's behavior. For example, large or small eigenvalues can tell you if the model is overfitting or underfitting.



In [4]:
# Lets define a square matrix
A = np.array([[4,2],[1,3]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("EigenValues : ",eigenvalues)
print("EigenVectors : ",eigenvectors)
# np.linalg.eig() is a simple method to calculate eigenValues and eigenVectors

EigenValues :  [5. 2.]
EigenVectors :  [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [6]:
# Revising singular value decomposition
# lets again define another matrix
B = np.array([[1,2,3],[4,5,6]])
U,sigma,VT = np.linalg.svd(B)
print("U : ",U)
print("Sigma : ",sigma)
print("VT : ",VT)

U :  [[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]
Sigma :  [9.508032   0.77286964]
VT :  [[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]


In [7]:
# The QR decomposition can indeed be performed on non-square matrices
# We have to make sure to have more rows than columns m>n m×n:
# QR decomposition factors a matrix A into:
# A=Q.R
# since we are coding it, it's not handy to explain mathematically. We have to apply Gram-Schmidt orthogonality to find Q
# which takes much time to calculate with a pen and paper.
C = np.array([[1, 2],
              [3, 4],
              [5, 6]])
Q ,R = np.linalg.qr(C)
print("Q : ",Q)
print("R : ",R)
# where Q: Orthogonal matrix.
# 𝑅: Upper triangular matrix.

Q :  [[-0.16903085  0.89708523]
 [-0.50709255  0.27602622]
 [-0.84515425 -0.34503278]]
R :  [[-5.91607978 -7.43735744]
 [ 0.          0.82807867]]


In [ ]:
# Cholesky Decomposition
# Define a symmetric positive-definite matrix
# Lets define what a positive-definite matrix is : A matrix 𝐴 is symmetric if it is equal to its transpose
# A matrix
# 𝐴 is positive-definite if: (𝑥𝑇)𝐴𝑥>0 for all nonzero vectors 𝑥


D = np.array([[4, 2],
              [2, 3]])
L = np.linalg.cholesky(D)

print("L:\n", L)
# It speeds up matrix inversion and log-determinant calculations, which are common in probabilistic models and regression.
#  Its numerical stability makes it a reliable choice in algorithms requiring precision.


In [8]:
E = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
# Let's compute rank for this matrix
rank = np.linalg.matrix_rank(E)
print("Rank:", rank)

Rank: 2


In [9]:
F = np.array([[1, 2],
              [3, 4]])
# note a point that finding trace is only applicable to square matrices since it is the sum of all diagonal elements.
det = np.linalg.det(F)
trace = np.trace(F)
print("Determinant:", det)
print("Trace:", trace)
# In ML, calculating determinant is iseful to realise the issues in the model or in the data.
# Positive det: Stable, invertible, desirable in most algorithms.
# Negative det: Indicates problems like non-positive definiteness, leading to instability or errors in training.

Determinant: -2.0000000000000004
Trace: 5


In [10]:
# Define a matrix G (the one for which we want to find the dominant eigenvector)
G = np.array([[2, 1],
              [1, 3]])

# Initial guess for the eigenvector (can be any vector)
v = np.array([1, 1])

# Repeat the process of multiplying by the matrix and normalizing the vector
for _ in range(10):  # Repeat 10 times to get a more accurate result
    v = np.dot(G, v)  # Multiply matrix G with the vector v
    v = v / np.linalg.norm(v)  # Normalize the resulting vector to unit length

# Print the final dominant eigenvector
print("Dominant Eigenvector:", v)


Dominant Eigenvector: [0.52574439 0.8506426 ]


In [11]:

from scipy.linalg import expm

# Define a matrix (example: a 2x2 matrix)
A = np.array([[1, 2],
              [3, 4]])

# Calculate the matrix exponential of A
A_exp = expm(A)

# Print the result
print("Matrix Exponential of A:\n", A_exp)

# Goal: We want to compute the matrix exponential of a square matrix.
# This is a generalization of the exponential function for matrices.
# For a scalar 𝑥, 𝑒 power 𝑥 is a well-known function.
# For matrices, we define the matrix exponential similarly, but it is computed using a power series expansion.
# Why Matrix Exponentials are Useful in Machine Learning:

# They are used in many advanced machine learning techniques, such as:
# Solving differential equations that describe how a system evolves over time.
# Stochastic processes, like Markov Chains or state transitions.
# Continuous time models, such as in neural networks or reinforcement learning.

Matrix Exponential of A:
 [[ 51.9689562   74.73656457]
 [112.10484685 164.07380305]]


In [12]:
# Importing necessary libraries
import numpy as np
from scipy.linalg import null_space

# Null Space: The null space of a matrix is the set of vectors that, when multiplied by the matrix, produce a zero vector.
# Why is it useful?: The null space helps in understanding how many degrees of freedom exist when solving a system of equations.
# If the null space has non-zero vectors, the system has infinitely many solutions.

# Define a matrix (example: a 2x2 matrix)
A = np.array([[2, 4],
              [1, 2]])

# Calculate the null space of A
null_space_A = null_space(A)

# null space in ML helps in reducing the complexity of models
# and selecting features that matter, making the model more efficient and less prone to overfitting.

# Print the result
print("Null Space of A:\n", null_space_A)


Null Space of A:
 [[-0.89442719]
 [ 0.4472136 ]]


In [14]:
# Condition Number in Machine Learning

# 1. Import required libraries
import numpy as np

# 2. Define a matrix to work with
A = np.array([[1, 2],
              [3, 4]])

# 3. Calculate the condition number of the matrix using np.linalg.cond()
condition_number = np.linalg.cond(A)

# 4. Display the condition number
print("Condition Number of A:", condition_number)

# Explanation of the condition number
#
# - The condition number of a matrix tells us how sensitive the solution of a system of linear equations is to small changes in the input.
# - If the condition number is high, the matrix is considered ill-conditioned, and small changes in the input can lead to large changes in the output.
# - In machine learning, high condition numbers in models can cause instability, especially when dealing with noisy data.
# - To deal with ill-conditioned problems, we can use regularization techniques such as Ridge or Lasso regression to stabilize the model.



Condition Number of A: 14.933034373659268
